name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Generate Documentation
        run: |
          # Команди для генерації документації
          # Для Javadoc в Java:
          ./gradlew javadoc

      - name: Publish documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          user_name: 'Your Name'
          user_email: 'your-email@example.com'
